### ISSUE TITLE
Error in `cal_plot_breaks()`

### ISSUE THREAD

**Issue by zjsty** [tidymodels/probably#130]
Dear professor,
I come with a problem when I run the example (https://www.tidyverse.org/blog/2022/11/model-calibration/#model-calibration)
the picture was followed. How up debug? 
<img width="572" alt="image" src="https://github.com/tidymodels/probably/assets/50436520/df5d3897-5275-4f14-bed4-beb115cf9d36">
Thanks.

**Comment by zjsty** [comment]
<img width="692" alt="image" src="https://github.com/tidymodels/probably/assets/50436520/f3ccb1f1-903e-4cd6-bbf3-3f4eba6d4900">
the problem again.

**Comment by topepo** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

**Comment by topepo** [comment]
The API has changed since that post We'll update it.

The error message has the solution: 

> ✖ This function does not work with grouped data frames.
> ℹ Apply `dplyr::ungroup()` and use the `.by` argument.

so use 

```r
combined %>%
    cal_plot_breaks(Class, .pred_good, .by = c(source))
```
